# Generated by Django 5.2.3 on 2025-07-03 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otplog',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='otplog',
            name='sent_via',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='otplog',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('login', 'Login Verification'), ('password_reset', 'Password Reset'), ('other', 'Other')], default='login', max_length=50),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login_attempt', 'Login Attempt'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('failed_login', 'Failed Login'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
