# Generated by Django 5.2.3 on 2025-07-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_fa_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('login_alerts', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
