# Generated by Django 5.2.3 on 2025-07-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitylog',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='securitylog',
            name='device_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
