# Generated by Django 5.2.3 on 2025-07-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_details_securitylog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='device_info',
        ),
        migrations.AddField(
            model_name='securitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
