# Generated by Django 5.2.3 on 2025-07-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_securitylog_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
