# Generated by Django 5.2.3 on 2025-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otpsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
