# Generated by Django 5.2.3 on 2025-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_otplog_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otpsetting',
            name='default_method',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='sms', max_length=20),
        ),
        migrations.AlterField(
            model_name='otpsetting',
            name='expiry_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
