# Generated by Django 5.2.3 on 2025-07-08 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_otpsetting_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitylog',
            old_name='user',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
