# Generated by Django 5.2.3 on 2025-07-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_user_securitylog_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginattempt',
            old_name='phone',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='securitylog',
            old_name='phone',
            new_name='user',
        ),
    ]
