# Generated by Django 5.2.3 on 2025-07-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customuser_options_alter_loginattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
