# Generated by Django 5.2.3 on 2025-07-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_securitylog_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='sent_via',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google Authenticator')], default='google', max_length=20),
        ),
        migrations.AlterField(
            model_name='otpsetting',
            name='default_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google Authenticator')], default='google', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='two_fa_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google Authenticator')], default='google', max_length=20),
        ),
    ]
