# Generated by Django 5.2.3 on 2025-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customuser_totp_secret_alter_otplog_sent_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
