# Generated by Django 5.2.3 on 2025-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customuser_is_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authenticator_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
