# Generated by Django 5.2.3 on 2025-07-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customuser_authenticator_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='two_fa_method',
            new_name='preferred_2fa_method',
        ),
    ]
